// Major US cities for the "target city" preference (searchable multi-select).
// Not exhaustive — students can pick several; matching prioritizes these, never
// hard-filters. Ordered roughly by metro size / relevance to training programs.
export const US_CITIES: string[] = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "Austin, TX",
  "San Jose, CA",
  "Fort Worth, TX",
  "Jacksonville, FL",
  "Columbus, OH",
  "Charlotte, NC",
  "Indianapolis, IN",
  "San Francisco, CA",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Boston, MA",
  "Nashville, TN",
  "Baltimore, MD",
  "Oklahoma City, OK",
  "Louisville, KY",
  "Portland, OR",
  "Las Vegas, NV",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Kansas City, MO",
  "Mesa, AZ",
  "Atlanta, GA",
  "Omaha, NE",
  "Colorado Springs, CO",
  "Raleigh, NC",
  "Long Beach, CA",
  "Virginia Beach, VA",
  "Miami, FL",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Bakersfield, CA",
  "Wichita, KS",
  "Arlington, TX",
  "Aurora, CO",
  "Tampa, FL",
  "New Orleans, LA",
  "Cleveland, OH",
  "Honolulu, HI",
  "Anaheim, CA",
  "Lexington, KY",
  "Stockton, CA",
  "Corpus Christi, TX",
  "Henderson, NV",
  "Riverside, CA",
  "Newark, NJ",
  "Saint Paul, MN",
  "Santa Ana, CA",
  "Cincinnati, OH",
  "Irvine, CA",
  "Orlando, FL",
  "Pittsburgh, PA",
  "St. Louis, MO",
  "Greensboro, NC",
  "Jersey City, NJ",
  "Anchorage, AK",
  "Lincoln, NE",
  "Plano, TX",
  "Durham, NC",
  "Buffalo, NY",
  "Chandler, AZ",
  "Chula Vista, CA",
  "Toledo, OH",
  "Madison, WI",
  "Gilbert, AZ",
  "Reno, NV",
  "Fort Wayne, IN",
  "North Las Vegas, NV",
  "St. Petersburg, FL",
  "Lubbock, TX",
  "Irving, TX",
  "Laredo, TX",
  "Winston-Salem, NC",
  "Chesapeake, VA",
  "Glendale, AZ",
  "Scottsdale, AZ",
  "Norfolk, VA",
  "Garland, TX",
  "Boise, ID",
  "Richmond, VA",
  "San Bernardino, CA",
  "Birmingham, AL",
  "Spokane, WA",
  "Rochester, NY",
  "Des Moines, IA",
  "Modesto, CA",
  "Fayetteville, NC",
  "Tacoma, WA",
  "Oxnard, CA",
  "Fontana, CA",
  "Columbus, GA",
  "Montgomery, AL",
  "Moreno Valley, CA",
  "Shreveport, LA",
  "Aurora, IL",
  "Yonkers, NY",
  "Akron, OH",
  "Huntington Beach, CA",
  "Little Rock, AR",
  "Augusta, GA",
  "Amarillo, TX",
  "Glendale, CA",
  "Mobile, AL",
  "Grand Rapids, MI",
  "Salt Lake City, UT",
  "Tallahassee, FL",
  "Huntsville, AL",
  "Grand Prairie, TX",
  "Knoxville, TN",
  "Worcester, MA",
  "Newport News, VA",
  "Brownsville, TX",
  "Overland Park, KS",
  "Santa Clarita, CA",
  "Providence, RI",
  "Fort Lauderdale, FL",
  "Chattanooga, TN",
  "Oceanside, CA",
  "Jackson, MS",
  "Rancho Cucamonga, CA",
  "Cape Coral, FL",
  "Springfield, MO",
  "Detroit, MI",
  "Memphis, TN",
  "Ann Arbor, MI",
  "Palo Alto, CA",
  "New Haven, CT",
  "Hartford, CT",
  "Iowa City, IA",
  "Charleston, SC",
  "Columbia, SC",
  "Gainesville, FL",
  "Rochester, MN",
];
